name: "s3 cache"
author: Dmitrii Sergeev
description: "S3 actions cache"
inputs:
  endpoint:
    description: "s3 / minio endpoint, see: https://docs.min.io/docs/javascript-client-api-reference.html"
    required: false
    default: s3.amazonaws.com
  region:
    description: "AWS region"
    required: false
  port:
    description: minio port
    required: false
  insecure:
    description: use insecure http connection to minio
    required: false
  accessKey:
    description: s3 / minio accessKey
    required: true
  secretKey:
    description: s3 / minio secretKey
    required: true
  sessionToken:
    description: s3 session token - required when using role
    required: false
  bucket:
    description: s3 / minio bucket
    required: true
  cache-list-keys:
    description: "List of keys to cache"
    default: ''
    required: false
  cache-list-keys-file:
    description: "List of keys to cache"
    default: ''
    required: false
runs:
  using: node20
  main: "../dist/saveOnly/index.js"
branding:
  icon: "archive"
  color: "gray-dark"
